### ISSUE TITLE
Swift 4?

### ISSUE THREAD

**Issue by jrazzano** [lucaslimapoa/NewsAPISwift#1]
Are there any plans to update this to support Swift 4?

**Comment by lucaslimapoa** [comment]
Hello @jrazzano,

I am migrating the client to the new API (v2) and I will add support for Swift 4.
I will be releasing this version in the next few days.

**Comment by jrazzano** [comment]
Thanks for the update!

**Comment by lucaslimapoa** [comment]
I finished the migration for the *Sources* and *Top Headlines* endpoints, along with Swift 4 and Carthage support. 

I will be adding the *Everything* endpoint in the next couple of days. 

Please, take a look at the [README](https://github.com/lucaslimapoa/NewsAPISwift/blob/master/README.md) for more instructions.
